version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "blps_db"
      POSTGRES_USER: "blps"
      POSTGRES_PASSWORD: "blps"
      PGDATA: "/var/lib/postgresql/data/blps_data"
    volumes:
      - ~/docker/postgres/blps/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"