version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "blps_db"
      POSTGRES_USER: "blps"
      POSTGRES_PASSWORD: "blps"
      PGDATA: "/var/lib/postgresql/data/blps_data"
    volumes:
      - ~/docker/postgres/blps/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  billing-postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "billing"
      POSTGRES_USER: "blps"
      POSTGRES_PASSWORD: "blps"
      PGDATA: "/var/lib/postgresql/data/billing"
    volumes:
      - ~/docker/postgres/billing/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  master-db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "master"
      POSTGRES_USER: "blps"
      POSTGRES_PASSWORD: "blps"
      PGDATA: "/var/lib/postgresql/data/master"
    volumes:
      - ~/docker/postgres/master/data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://localhost:9092,DOCKER://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9001
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zookeeper
